# Identificación del proyecto en SonarQube
sonar.projectKey=Apoya.pe
sonar.projectName=Mi Proyecto Vue + Laravel
sonar.projectVersion=1.0

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

# TU TOKEN AQUÍ
sonar.login=sonar-scanner.bat -D"sonar.projectKey=Apoyo" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000" -D"sonar.token=sqp_93b38d2c894d98a3d1a627c2ada72475e9fb41c5"

# Rutas del proyecto
sonar.sources=app,resources/js,resources/views,routes

# Archivos a excluir
sonar.exclusions=**/node_modules/**,**/vendor/**,public/**
